name: PxVisualizer CD

run-name: CD for ${{ github.ref_name }}

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "PxVisualizer CI"
    types:
      - completed
    branches:
      - dev
      - test
      - main

env:
  ENV: ${{ github.ref == 'refs/heads/dev' && 'd' ||
    github.ref == 'refs/heads/test' && 't' ||
    github.ref == 'refs/heads/main' && 'latest' }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [21.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
  
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci --no-audit --quiet --prefer-offline

    - name: Build
      run: npm run build

    - name: Set current version
      run: |
        commitHash=$(git rev-parse HEAD)
        echo "commitHash=$commitHash" >> $GITHUB_ENV
        echo $commitHash > dist/version.txt
        echo $commitHash

    - name: Validate version bump
      run: npm run version-helper validate
      
    - name: Set prerelease version
      run: npm run version-helper setpreversion
      if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/test'

    - name: Publish
      run: npm publish --tag ${{ ENV }} --git-tag-version false
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}