name: PxVisualizer CI

run-name: ${{ github.event_name == 'pull_request' &&
  format('CI for PR {0}', github.event.pull_request.number) || 
  format('CI for {0}', github.event.head_commit.message) }}

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - test
      - main
  workflow_dispatch:

env:
  ENV: ${{ github.event.workflow_run.head_branch == 'dev' && 'd' ||
    github.event.workflow_run.head_branch == 'test' && 't' ||
    github.event.workflow_run.head_branch == 'main' && 'latest' ||
    'feature' }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [21.x]
    
    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Test 1A
      run: echo ${{ github.event.workflow_run.head_branch }}}

    - name: Test 1B
      run: echo ${{ ENV.env }}}

    - name: Test 2A-1
      run: echo "Test 2A-1"
      if: env.ENV == 'd' || env.ENV == 't'

    - name: Test 2A-2
      run: echo "Test 2A-2"
      if: ${{ env.ENV == 'd' || env.ENV == 't' }}

    - name: Test 2B-1
      run: echo "Test 2B-1"
      if: env.ENV == 't' || env.ENV == 'latest'

    - name: Test 2B-2
      run: echo "Test 2B-2"
      if: ${{ env.ENV == 't' || env.ENV == 'latest' }}

    - name: Test 2C-1
      run: echo "Test 2C-1"
      if: env.ENV == 'latest' || env.ENV == 'd'

    - name: Test 2C-2
      run: echo "Test 2C-2"
      if: ${{ env.ENV == 'latest' || env.ENV == 'd' }}

    - name: Test 3C-1
      run: echo "Test 3C-1"
      if: env.ENV == 'feature' || env.ENV == 'd'

    - name: Test 3C-2
      run: echo "Test 3C-2"
      if: ${{ env.ENV == 'feature' || env.ENV == 'd' }}

    - name: Test 4
      run: echo "This shouldn't run, and if it does, I am very confused"
      if: env.ENV == 'd' || env.ENV == 't'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm run test:ci

    - name: Validate version bump
      run: npm run version-helper validate
      if: github.event_name == 'pull_request'