name: PxVisualizer CI

on:
  push:
    branches:
      - master
      - test
      - feature/*
      - bugfix/*
      - develop
  pull_request:
    branches:
      - master
      - test
      - feature/*
      - bugfix/*
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm run test:ci

    - name: Validate version bump
      run: npm run version-helper validate
      if: github.event_name == 'pull_request'

      # testing more