name: dependabot Version Increment

run-name: ${{ format('dependabot Version Increment for PR {0}', github.event.pull_request.number) }}

on:
  pull_request:
    branches:
      - 'dev'

jobs:
 dependabot_version_increment:
    # TEST if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Get current version number from main branch
        run: |
          git fetch origin main
          git checkout origin/main -- package.json
          echo "CURRENT_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
          echo "Current main version is $CURRENT_VERSION"

      - name: Checkout PR branch
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git pull origin ${{ github.event.pull_request.head.ref }}

      - name: Get version number from PR branch
        run: |
          echo "Content of package.json in PR branch:"
          cat package.json
          PR_VERSION=$(jq -r '.version' package.json)
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_ENV
          echo "Version in PR branch is $PR_VERSION"

      - name: Compare and increment version number
        run: |
          echo "Comparing versions: $CURRENT_VERSION and $PR_VERSION"
          if [ "$CURRENT_VERSION" = "$PR_VERSION" ]; then
            npm version patch --no-git-tag-version
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add package.json
            git commit -m "Version bump from $PR_VERSION to $(jq -r '.version' package.json)"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "Version number in PR branch is already up-to-date. No action taken."
          fi