name: PxVisualizer SonarScan

run-name: ${{ github.event_name == 'pull_request' &&
  format('SonarScan for PR {0}', github.event.pull_request.number) || 
  format('SonarScan for {0}', github.event.head_commit.message) }}

on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'dev'

jobs:
 sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -D sonar.organization=statisticsfinland-github
            -D sonar.projectKey=StatisticsFinland_PxVisualizer
