name: Test B

run-name: Test B for ${{ github.event.workflow_run.head_branch }}

on:
  workflow_run:
    workflows:
      - "Test A"
    types:
      - completed
    branches:
      - dev
      - test
      - main
      - feature/*
      - bugfix/*
  workflow_dispatch:
jobs:
  testb:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
     
     - name: Test B Step 1
       run: echo "Test B Step 1  ${{ github.event.workflow_run.head_branch }}"
